# -*- coding: utf-8 -*-
"""part_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IUh3aNMfI-z4Bi2uT_ULdzEXaDECZK1X
"""

# !pip install scipy matplotlib numpy

"""
Part 4: Gradient Descent in Code
==================================
Converts the Part 3 manual calculation into working Python code, using the
SAME convention as the manual write-up:
    - m is a 2-vector [m1, m2]
    - b is carried as a vector aligned with the samples, b = [b1, b2],
      updated elementwise just like m (NOT collapsed to a single scalar)
    - y_hat = X @ m + b   (elementwise add of the two length-2 vectors)

scipy.optimize.approx_fprime is used to numerically differentiate the MSE
cost function -- this satisfies "use SciPy to compute the derivative" --
and every update step is written out explicitly (no hidden .fit() call).
"""

import numpy as np
from scipy.optimize import approx_fprime
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

# ---------------------------------------------------------------------
# Data (same as Part 3)
# ---------------------------------------------------------------------
X = np.array([[1, 3], [4, 10]], dtype=float)
y = np.array([5, 6], dtype=float)

ALPHA = 0.01
N_ITERS = 4          # one iteration per group member


# ---------------------------------------------------------------------
# The "equation" as a single function of a flat parameter vector
# theta = [m1, m2, b1, b2], so SciPy can differentiate it as one unit.
# ---------------------------------------------------------------------
def predict(theta, X):
    m = theta[:2]
    b = theta[2:4]
    return X @ m + b


def cost_fn(theta, X, y):
    """Mean Squared Error, J(theta) = J(m1, m2, b1, b2)."""
    y_hat = predict(theta, X)
    return np.mean((y_hat - y) ** 2)


def scipy_gradient(theta, X, y, eps=1e-8):
    """
    Generic function that accepts an 'equation' (here: cost_fn) and returns
    its derivative (gradient) at theta, computed numerically by SciPy --
    no hand-typed analytic gradient formula is plugged in here.
    """
    return approx_fprime(theta, cost_fn, eps, X, y)


# ---------------------------------------------------------------------
# Gradient Descent loop -- every step is visible, nothing abstracted away
# ---------------------------------------------------------------------
def run_gradient_descent(theta0, X, y, alpha=ALPHA, n_iters=N_ITERS):
    theta = theta0.copy()
    history = {"m1": [], "m2": [], "b1": [], "b2": [], "mse": [], "theta": []}

    for i in range(n_iters):
        mse_now = cost_fn(theta, X, y)
        history["m1"].append(theta[0])
        history["m2"].append(theta[1])
        history["b1"].append(theta[2])
        history["b2"].append(theta[3])
        history["mse"].append(mse_now)
        history["theta"].append(theta.copy())

        grad = scipy_gradient(theta, X, y)    # <- SciPy computes the derivative
        theta = theta - alpha * grad           # explicit elementwise update

    # record the final state too
    history["m1"].append(theta[0])
    history["m2"].append(theta[1])
    history["b1"].append(theta[2])
    history["b2"].append(theta[3])
    history["mse"].append(cost_fn(theta, X, y))
    history["theta"].append(theta.copy())
    return theta, history


if __name__ == "__main__":
    theta0 = np.array([-1.0, 2.0, 1.0, 1.0])  # [m1, m2, b1, b2]

    theta_final, hist = run_gradient_descent(theta0, X, y)

    print("Initial theta [m1, m2, b1, b2] :", theta0)
    print("Final   theta [m1, m2, b1, b2] :", np.round(theta_final, 4))
    print(f"Final MSE                      : {hist['mse'][-1]:.6f}")

    print("\nAll iterations (should match the manual Part 3 calculation):")
    for i in range(len(hist["mse"])):
        print(f"  iter {i}: m=[{hist['m1'][i]:.4f}, {hist['m2'][i]:.4f}]  "
              f"b=[{hist['b1'][i]:.4f}, {hist['b2'][i]:.4f}]  "
              f"MSE={hist['mse'][i]:.4f}")

    # Final predictions using the final m, b
    y_hat_final = predict(theta_final, X)
    print(f"\nFinal predictions ŷ = {np.round(y_hat_final, 4)}  vs. true y = {y}")

    # -------------------------------------------------------------
    # Plot 1: how m and b change over iterations
    # -------------------------------------------------------------
    iters = np.arange(len(hist["mse"]))
    fig1, ax1 = plt.subplots(figsize=(7, 4.5))
    ax1.plot(iters, hist["m1"], label="m1", marker="o", markersize=5)
    ax1.plot(iters, hist["m2"], label="m2", marker="s", markersize=5)
    ax1.plot(iters, hist["b1"], label="b1", marker="^", markersize=5)
    ax1.plot(iters, hist["b2"], label="b2", marker="v", markersize=5)
    ax1.set_xlabel("Iteration")
    ax1.set_ylabel("Parameter value")
    ax1.set_title("Parameter Evolution over Gradient Descent Iterations")
    ax1.legend()
    ax1.grid(alpha=0.3)
    fig1.tight_layout()
    fig1.savefig("params_over_iterations.png", dpi=150)

    # -------------------------------------------------------------
    # Plot 2: how error (MSE) changes over iterations
    # -------------------------------------------------------------
    fig2, ax2 = plt.subplots(figsize=(7, 4.5))
    ax2.plot(iters, hist["mse"], color="crimson", marker="o", markersize=6)
    ax2.set_xlabel("Iteration")
    ax2.set_ylabel("Mean Squared Error")
    ax2.set_title("Training Error (MSE) over Gradient Descent Iterations")
    ax2.grid(alpha=0.3)
    fig2.tight_layout()
    fig2.savefig("error_over_iterations.png", dpi=150)

    print("\nSaved plots: params_over_iterations.png, error_over_iterations.png")
